### ISSUE TITLE
兼容问题

### ISSUE THREAD

**Issue by anCheng1994** [Mater1996/vue-photo-zoom-pro#1]
为什么dome上safari兼容都没有问题  自己使用的时候存在safari取不到top值

**Comment by Mater1996** [comment]
@anCheng1994 兼容问题，建议引入polyfill来解决

**Comment by anCheng1994** [comment]
@Mater1996  你好 可以说的具体点吗  或者有相关链接吗

**Comment by Mater1996** [comment]
@anCheng1994 https://babeljs.io/docs/en/babel-polyfill/

**Comment by anCheng1994** [comment]
是scrollTop的问题 
initSelectorProperty方法中的scrollTop 需要使用兼容性写法
scrollTop = document.documentElement.scrollTop || window.pageYOffset || document.body.scrollTop;

**Comment by Mater1996** [comment]
好的 谢谢指出 我会在之后更新这个这个问题

**Comment by skypiaoyizhe** [comment]
直接引用后控制台报错 did you register the component correctly? For recursive components, make sure to provide the "name"

**Comment by Mater1996** [comment]
@skypiaoyizhe 没有注册组件吗

**Comment by skypiaoyizhe** [comment]
> @skypiaoyizhe 没有注册组件吗
怎么注册组件  我把你的/src/components/vue-photo-zoom-pro.vue单独拿出来使用没问题
