### ISSUE TITLE
有时候没效果，报如下这个错误，咋弄，大佬？

### ISSUE THREAD

**Issue by low123456** [Mater1996/vue-photo-zoom-pro#14]
![image](https://user-images.githubusercontent.com/40919828/113666412-d4fb9e80-96e1-11eb-83cc-8a17a7d442ed.png)
![image](https://user-images.githubusercontent.com/40919828/113666439-e0e76080-96e1-11eb-9097-568d65e05a98.png)

**Comment by Mater1996** [comment]
可以提供下配置或者提供下最小可复现仓库么？也可以在codepen里fork一份demo并复现错误给我一下
