### ISSUE TITLE
如何解决原图被scale放大后，放大镜定位的重置问题？

### ISSUE THREAD

**Issue by koukouzaki** [Mater1996/vue-photo-zoom-pro#19]
就是背景图被transform的scale放大缩小了，移上去的放大镜如何重置定位呢？目前是会偏离原来的位置。

**Comment by Mater1996** [comment]
transform 不会影响原有图片的大小，所以内部获取的高宽还是原来的高宽
可以把photo-zoom-pro内部的img设置透明，然后覆盖到现有的img上面，然后把透明的img调整width和height跟随外部的transofrm进行变动
或者也可以修改部分源码，把获取img高宽的方法自定义一下

**Comment by Mater1996** [comment]
是修改了哪里的背景图？ 可以给个repo复现一下吗？https://codesandbox.io/

**Comment by koukouzaki** [comment]
因为我这边还需要zoomIn，zoomOut的功能，所以会放大缩小那张原图，一旦放大缩小后，用放大镜就会有定位偏移不准的问题，不知道怎样可以触发一下刷新，让放大镜重新获取最新的原图。

**Comment by Mater1996** [comment]
目前是手动调用组件的reset方法来重新计算边界信息
看起来这也是这个组件的问题，我抽空重新整理下边界信息的自动重新计算

**Comment by koukouzaki** [comment]
所以不知道怎么处理才能正常。貌似得去改动组件源码的内容了

**Comment by mater1996** [comment]
辛苦发一个复现repo吧

**Comment by Mater1996** [comment]
原因是因为设置放大器的位置以及获取的宽度被scale放大了, 所以位置被css 重新 * 2 导致中心点偏移错误
不建议使用scale对该组件进行放大，因为内部使用了absolute进行偏移，会导致放大器以及mask的位置被css放大
