### ISSUE TITLE
vue-photo-zoom-pro传入的图片有些放大镜无效果

### ISSUE THREAD

**Issue by Variable-1760** [mater1996/vue-photo-zoom-pro#22]
图片大小和格式都测试，自己分析不出来是哪儿出问题
```html
<vue-photo-zoom-pro 
            :out-zoomer="outZoomFlag"
            :width="zoomWidth" 
            :out-zoomer-style="{'z-index': 2}" 
            :url="http://yucongxinxikeji.oss-cn-hangzhou.aliyuncs.com/WEBSITE_PRODUCT_PICTURE/20190104%20(3)YC001WCpb3162211000996477nYC001WCHdT1629085272244Yus.png">
            <template slot="zoomer">
              <div class="ks-imagezoom-wrap"></div>
            </template>
</vue-photo-zoom-pro>
```
就是放大镜边框区域有展现，但就是放大图没有显示
![photo-zoom-pro放大图片问题](https://user-images.githubusercontent.com/89447429/130581160-a807132d-18fb-425d-81a0-7be3410127f7.png)
希望大佬帮忙解解惑

**Comment by Variable-1760** [comment]
![图片信息](https://user-images.githubusercontent.com/89447429/130582487-1152be5e-36ac-41c8-bb50-8f891b81b9b3.png)
![页面dom定位原因](https://user-images.githubusercontent.com/89447429/130582558-633b2f1c-0fc3-4681-9c4c-efc57fa41646.png)

**Comment by mater1996** [comment]
hello 这是因为background-image 在老版本的url 没有用引号包起来，你可以使用 >>>  手动修改下内部的 background-image样式即可，或者使用新的版本，虽然使用方式会有变化

**Comment by mater1996** [comment]
hello, 这是因为 img-out-show 上的background-image的url没有用引号包裹，这是一个bug，你可以手动覆盖下background-image，或者使用新的版本

**Comment by mater1996** [comment]
这里有一个demo你可以跟着写一下
https://codesandbox.io/s/unruffled-nova-glv60?file=/src/App.vue

**Comment by Variable-1760** [comment]
感谢大佬回复，参考您的demo，问题已经解决了
我这个是动态图片放大镜效果。
![问题解决](https://user-images.githubusercontent.com/89447429/130723979-0a9af3d7-e5ef-45d3-9562-8156d653e56d.png)
