### ISSUE TITLE
It's not possible to import two different things with the same name. Error 'Parsing error: Identifier "vuePhotoZoomPro" has already been declared'

### ISSUE THREAD

**Issue by Zitface** [mater1996/vue-photo-zoom-pro#28]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by mater1996** [comment]
It seems to be a documentation problem. I will fix it.

**Comment by mater1996** [comment]
https://github.com/mater1996/vue-photo-zoom-pro/releases/tag/2.2.1
