### ISSUE TITLE
放大镜的高度设置失败

### ISSUE THREAD

**Issue by mu-shan** [Mater1996/vue-photo-zoom-pro#3]
`<vue-photo-zoom-pro` v-if="infoData.headImageUrl" :url="infoData.headImageUrl" :width="150" :height="150"></vue-photo-zoom-pro>`

**Comment by mu-shan** [comment]
![image](https://user-images.githubusercontent.com/23648843/71609825-94e86a80-2bc6-11ea-9390-a4136c978f07.png)

**Comment by mu-shan** [comment]
https://user-images.githubusercontent.com/23648843/71609845-b21d3900-2bc6-11ea-900a-0037ae08fc18.png

**Comment by Mater1996** [comment]
会有错误提示吗， 代码貌似没有问题

**Comment by mu-shan** [comment]
没有报错，还是按文档加的 :height



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xiaohanbai"<notifications@github.com&gt;; 
发送时间: 2019年12月31日(星期二) 下午2:46
收件人: "Mater1996/vue-photo-zoom-pro"<vue-photo-zoom-pro@noreply.github.com&gt;; 
抄送: "一块二的金帝"<1715722187@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Mater1996/vue-photo-zoom-pro] 放大镜的高度设置失败 (#3)




会有错误提示吗， 代码貌似没有问题

**Comment by mu-shan** [comment]
可以加下 QQ吗，我的 1715722187




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xiaohanbai"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月31日(星期二) 下午2:46
收件人:&nbsp;"Mater1996/vue-photo-zoom-pro"<vue-photo-zoom-pro@noreply.github.com&gt;;
抄送:&nbsp;"一块二的金帝"<1715722187@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Mater1996/vue-photo-zoom-pro] 放大镜的高度设置失败 (#3)




会有错误提示吗， 代码貌似没有问题
