### ISSUE TITLE
UIEvent is not defined

### ISSUE THREAD

**Issue by Zitface** [mater1996/vue-photo-zoom-pro#30]
Hi.

Thanks for fixing the documentation issue the other day - i am now using your component with great pleasure :)
However, i keep running into a new error everytime i refresh my vue app:

```
ReferenceError
UIEvent is not defined
```

The error is thrown consistently on line **3713** in file **vue-photo-zoom-pro.js.**

Any suggestions to how i might fix that?

**Comment by mater1996** [comment]
What is your browser environment?

**Comment by Zitface** [comment]
Chrome, version 96.0.4664.93, 64-bit

**Comment by mater1996** [comment]
I haven't had that problem, can you provide a screenshot or repo?

**Comment by mater1996** [comment]
> Chrome, version 96.0.4664.93, 64-bit

I haven't had that problem, can you provide a screenshot or repo?

**Comment by Zitface** [comment]
![image](https://user-images.githubusercontent.com/11219465/145772116-471fe7a9-08a0-4478-bc4d-6301461188cc.png)

**Comment by Zitface** [comment]
It happens after i have initialized the component, and then refresh the browser window (f5).

**Comment by mater1996** [comment]
Looks like it's SSR, right?

**Comment by Zitface** [comment]
Yeah it is, nuxt SSR.

**Comment by mater1996** [comment]
This is because there are no `window` in SSR environments, and I think you need to skip rendering `vue-photo-zoom-pro` in SSR environments.

**Comment by Zitface** [comment]
I included the module as a plugin with flag ssr: false, this fixed the issue. Once again. thank you.

**Comment by zzzli** [comment]
怎么做的？
