### ISSUE TITLE
安装完最新版本的，启动项目报错，是怎么回事？

### ISSUE THREAD

**Issue by lvr1997** [mater1996/vue-photo-zoom-pro#32]
安装完最新版本的，启动项目报错，是怎么回事？
报错信息如下：
These dependencies were not found:

* E:\Code\kd-shop-vue\node_modules\core-js\modules\es6.array.iterator.js in ./src/main.js
* E:\Code\kd-shop-vue\node_modules\core-js\modules\es6.object.assign.js in ./src/main.js
* E:\Code\kd-shop-vue\node_modules\core-js\modules\es6.promise.js in ./src/main.js
* E:\Code\kd-shop-vue\node_modules\core-js\modules\es7.promise.finally.js in ./src/main.js

**Comment by mater1996** [comment]
缺少core-js,尝试安装core-js.
