### ISSUE TITLE
动态改变图片url会闪现img src 出错的样式

### ISSUE THREAD

**Issue by whypool** [Mater1996/vue-photo-zoom-pro#4]
在img标签加个判断

> v-show="imgLoadedFlag && url"

**Comment by Mater1996** [comment]
不建议这么做，这样会导致图片高度瞬间的坍塌，如果显示出错样式的话，可以在css 设定 img[src=""] 的情况

**Comment by Mater1996** [comment]
确实可以这么做，也可以使用css img[src=""] 去间接设置样式，省去了javascript 的介入
