### ISSUE TITLE
关于vue-photo-zoom-pro.css丢失的问题

### ISSUE THREAD

**Issue by HeyWeCome** [mater1996/vue-photo-zoom-pro#43]
**问题描述**
今天我运行`npm install vue-photo-zoom-pro`后，发现引入`vue-photo-zoom-pro.css`失败。并且切换2.4.3版本解决css丢失问题。

然后我打开dist查看文件目录，发现css文件丢失，请问能否解决一下？
![image](https://user-images.githubusercontent.com/30435835/167981955-2fc9c7f3-2622-4b1a-99a6-854c9bfba742.png)

**Comment by mater1996** [comment]
@HeyWeCome 引入失败的版本是多少？

**Comment by HeyWeCome** [comment]
版本为：2.5.0

**Comment by mater1996** [comment]
@HeyWeCome install的版本错了，这个应该和你的lock版本有关系。
你可以看下图片里的package.json，应该是很老的版本了，老版本是没有css的，css是直接写入到js里然后创建style标签的。

**Comment by HeyWeCome** [comment]
@mater1996 我刚验证了一下，确实是这个问题，感谢，我现在把项目切换为新版本
